name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Chekout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        echo "inicio del loginazo"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "fin del loginazo"
        
    - name: Build docker image
      run: |
        docker build -t franciscochdev/graphql-actions:0.0.2 .

    - name: Push docker image
      run: |
        docker push -t franciscochdev/graphql-actions:0.0.2 .
